name: Latest blog post workflow
on: 
    workflow_dispatch: 
    schedule:
        - cron: '0 * * * *'
jobs: 
    update-readme-with-blog: 
        name: Update this repo's README with latest blog posts
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v5
            - uses: gautamkrishnar/blog-post-workflow@master
              with: 
                max_post_count: "7"
                feed_list: "https://medium.com/feed/@yoshiyuki.watanabe"
